# Create groups user deploy.
- name: "Create user groups"
  group:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ user_groups }}"

# Create users account and attach and their own group list.
- name: "Create deploy account"
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    comment: "{{ item.comment }}"
    shell: "{{ item.shell }}"
  with_items: "{{ users }}"
