# 6. Install apache2 and configure it.

#- name: Stop apache2 service
#  service:
#    name: apache2
#    state: stopped

#- name: Ensure apache2 is not installed.
#  apt:
#  name: apache2
#  state: absent

- name: Ensure apache2 is at the latest version
  apt: 
    name: apache2
    state: latest

- name: Start apache2
  service:
    name: apache2
    state: started

- name: /var/www/
  file:
    path:  /var/www/
    owner: "{{username}}"
    state: directory
    group: "root"
    mode: 0755
    recurse: yes

# create a directory if it doesn't exist
- name: Create directory /var/www/html/monitoring
  file:
    path: /var/www/html/monitoring
    owner: "{{username}}"
    state: directory
    mode: 0755
