# Please se this for more details : https://gist.github.com/thomasfr/9691385
#- name: ""
#  include_tasks: "install-git.yml"

#- name: ""
#  include_tasks: "install-user.yml"

#- name: ""
#  include_tasks: "install-key.yml"
# 3. Add your ssh public key to the authorized_keys file of the created user.
- name: Create directory "{{directory_home}}/.ssh"
  file:
    path: "{{directory_home}}/.ssh"
    state: directory
    owner: "{{username}}"
    group: "{{username}}"

- name: Copy id_rsa.gitlab.pub to "~/.ssh/authorized_keys"
  copy:
    src: files/id_rsa.gitlab.pub 
    dest: "{{directory_home}}/.ssh/authorized_keys"
    owner: "{{username}}"
    group: "{{username}}"
    mode: 400

#- name: ""
#  include_tasks: "install-repo.yml"
# 4. Create a git bare repo for your project.
- name: Create directory {{directory_repo}}
  file:
    path: "{{directory_repo}}"
    state: directory
    owner: "{{username}}"
    group: "{{username}}"

- name: Create directory {{directory_repo}}
  shell: git -C {{directory_repo}} init --bare
  args:
    executable: /bin/bash

# 5. Copy the post-receive script to the hooks dir of the created bare repository. 
- name: Copy post-receive to hooks/post-receive on server
  copy: 
    src: files/post-receive
    dest: "{{directory_repo}}/hooks/post-receive"#

- name: Set chmod +x the post-receive script
  file: 
    path: "{{directory_repo}}/hooks/post-receive"
    mode: "a+x"

- name: Fix {{directory_repo}} permissions
  file: 
    path: "{{directory_repo}}"
    owner: "{{username}}"
    group: "{{username}}" 
    mode: 0775
    state: directory
    recurse: yes

#- name: ""
#  include_tasks: "install-web.yml"
- name: Ensure apache2 is at the latest version
  apt: 
    name: apache2
    state: latest

- name: Start apache2
  service:
    name: apache2
    state: started

- name: /var/www/
  file:
    path:  /var/www/
    owner: "{{username}}"
    state: directory
    group: "root"
    mode: 0755
    recurse: yes

# create a directory if it doesn't exist
- name: Create directory /var/www/html/monitoring
  file:
    path: /var/www/html/monitoring
    owner: "{{username}}"
    state: directory
    mode: 0755


