# Please se this for more details : https://gist.github.com/thomasfr/9691385

# 1. Install git package to the latest version.
- name: Install git package to the latest version
  apt:
    name: git
    state: present

# 2. It is not possible to interactively login as this user.
- name: Create a user call git on the server
  user:
    name: "{{username}}"
    groups:
    state: present
    shell: /usr/bin/git-shell
    createhome: yes
    home: "/home/{{username}}"

# 3. Add your ssh public key to the authorized_keys file of the created user.
- name: Create directory "{{directory_home}}/.ssh"
  file:
    path: "{{directory_home}}/.ssh"
    state: directory

- name: Copy id_rsa.gitlab.pub to "{{directory_home}}/.ssh/authorized_keys"
  copy:
    src: files/id_rsa.gitlab.pub 
    dest: "{{directory_home}}/.ssh/authorized_keys"

# 4. Create a git bare repo for your project.
- name: Create directory {{directory_repo}}
  file:
    path: "{{directory_repo}}"
    state: directory

- name: Create directory {{directory_repo}}
  shell: git -C "{{directory_repo}}" init --bare
  args:
    executable: /bin/bash

# 5. Copy the post-receive script to the hooks dir of the created bare repository. 
- name: Copy the post-receive script into hooks/post-receive on server
  copy: 
    src: files/post-receive
    dest: "{{directory_repo}}/hooks/post-receive"

- name: Set chmod +x the post-receive script
  file: 
    path: "{{directory_repo}}/hooks/post-receive"
    mode: "a+x"

# 6. Set ownership and permissions of the web directory.
- name: Set ownership and permissions of the web directory
  file:
    path: "/var/www"
    state: directory
    recurse: yes
    owner: root
    group: "{{username}}"
    mode: 0775
