username: pi

directory_home: "/home/{{username}}"
directory_repo: "/home/{{username}}/.fantastics/monitoring"
git_remote_url: "git@192.168.1.73:~/monitoring"
ssh_private_key: "/home/{{username}}/.ssh/id_rsa.fantastics"
