# Playbook installation d'un robot + configuration + monitoring.

# Clone le dépôt du robot dans le dépertoire de deploy.
- name: "CLONE ROBOT REPOSITORY"
  hosts: "raspberry"
  roles:
    - role: "Roles/robotgitlab"

# Start the robot on boot os by adding a cron job.
- name: "ADD CRON JOB FOR THE ROBOT"
  hosts: "raspberry"
  roles:
    - role: "Roles/robotcron"