# Remove previous cron job for robot program.
- name : Remove previous robot cron job 
  cron :
    name  : Check update every minute.
    state : absent

# Check update every minute.
- name: "Check update every minute"
  cron:
    name: Check update every minute.
    job: "/home/pi/.robot/robot/Robot.sh auto"
    state: present
    user: "pi"
