# Remove previous cron job for robot program.
- name : Remove previous robot cron job 
  cron :
    name  : Activate the robot once at system startup.
    state : absent

# Activate the robot once at system startup.
- name: "Activate the robot once at system startup"
  cron:
    name: Activate the robot once at system startup.
    job: "/home/pi/.robot/robot/Robot.sh auto"
    special_time: reboot
    state: present
    user: "deploy"
