# Create .ssh folder if not exist in the home directory.
- name: Create directory {{directory_home}}/.ssh
  file:
    path: "{{directory_home}}/.ssh"
    state: directory
    owner: "{{username}}"
    group: "{{username}}"

# Copying private key to the client machine.
- name: Delete previous {{directory_home}}/.ssh/id_rsa.fantastics
  file:
    path: "{{directory_home}}/.ssh/id_rsa.fantastics"
    state: absent

- name: Copy id_rsa.fantastics to {{directory_home}}/.ssh/id_rsa.fantastics
  copy:
    src: files/id_rsa.fantastics
    dest: "{{directory_home}}/.ssh/id_rsa.fantastics"
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0400

# Copying ssh config file to the client machine.
- name: Delete previous {{directory_home}}/.ssh/config
  file:
    path: "{{directory_home}}/.ssh/config"
    state: absent

- name: Configuring {{directory_home}}/.ssh/config for git
  template:
    src: config.j2
    dest: "{{directory_home}}/.ssh/config"
    owner: "{{username}}"
    group: "{{username}}"
