# Copying private key to the client machine.

- name: Transfer the scripts to config git repository
  template: 
    src: Configure.sh.j2
    dest: "{{directory_repo}}/Configure.sh"
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0777

- name: Transfer the script to push automatically
  copy: 
    src: files/Monitoring.sh
    dest: "{{directory_repo}}/Monitoring.sh"
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0777

- name: Transfer the script eZServerMonitor.sh
  copy:
    src: files/eZServerMonitor.sh
    dest: "{{directory_repo}}/eZServerMonitor.sh"
    owner: "{{username}}"
    group: "{{username}}"
    mode: 0777

- name: Fix {{directory_repo}} permissions
  file: 
    path: "{{directory_repo}}"
    owner: "{{username}}"
    group: "{{username}}" 
    mode: 0775
    state: directory
    recurse: yes
